-- ============================================================
-- Migration: Guest Visits + Investment Group Invite Codes
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- 1. Guest Visits Table
-- Tracks every person who enters the app via Guest Access
create table if not exists guest_visits (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  visited_at timestamptz not null default now()
);

-- Allow anyone (including unauthenticated visitors) to insert a visit row
alter table guest_visits enable row level security;
create policy "anon can log visit" on guest_visits
  for insert with check (true);

-- Only authenticated users can read visit logs (for your own admin view)
create policy "auth can read visits" on guest_visits
  for select using (auth.role() = 'authenticated');

-- ============================================================

-- 2. Investment Group Invite Codes
-- Each group gets one unique alphanumeric invite code.
-- Members share this code; anyone with it can join the group.

alter table family_groups
  add column if not exists invite_code text unique;

-- Generate a random 8-char alphanumeric code for existing groups
-- (Run once; new groups will get codes generated by the app)
update family_groups
set invite_code = upper(
  substring(md5(random()::text || id::text), 1, 4) ||
  substring(md5(id::text || now()::text), 1, 4)
)
where invite_code is null;

-- Index for fast lookup when joining with a code
create index if not exists idx_family_groups_invite_code
  on family_groups (invite_code);

-- ============================================================
-- Done. Verify with:
--   select * from guest_visits;
--   select id, group_name, invite_code from family_groups;
-- ============================================================
